route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#alert'
            api_url: 'https://hooks.slack.com/services/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'
