global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  # pcct1
  - job_name: 'nodeexporter_pcct1'
    static_configs:
      - targets: ['pcct1:9910']
  - job_name: 'cadvisor_pcct1'
    static_configs:
      - targets: ['pcct1:9808']
  # pcct2
  - job_name: 'nodeexporter_pcct2'
    static_configs:
      - targets: ['pcct2:9910']
  - job_name: 'cadvisor_pcct2'
    static_configs:
      - targets: ['pcct2:9808']
  # pcct3
  - job_name: 'nodeexporter_pcct3'
    static_configs:
      - targets: ['pcct3:9910']
  - job_name: 'cadvisor_pcct3'
    static_configs:
      - targets: ['pcct3:9808']
  # pcct4
  - job_name: 'nodeexporter_pcct4'
    static_configs:
      - targets: ['pcct4:9910']
  - job_name: 'cadvisor_pcct4'
    static_configs:
      - targets: ['pcct4:9808']
  # pcst1
  - job_name: 'nodeexporter_pcst1'
    static_configs:
      - targets: ['pcst1:9910']
  - job_name: 'cadvisor_pcst1'
    static_configs:
      - targets: ['pcst1:9808']
  # pcst2
  - job_name: 'nodeexporter_pcst2'
    static_configs:
      - targets: ['pcst2:9910']
  - job_name: 'cadvisor_pcst2'
    static_configs:
      - targets: ['pcst2:9808']
  # pcst3
  - job_name: 'nodeexporter_pcst3'
    static_configs:
      - targets: ['pcst3:9910']
  - job_name: 'cadvisor_pcst3'
    static_configs:
      - targets: ['pcst3:9808']
  # pcst4
  - job_name: 'nodeexporter_pcst4'
    static_configs:
      - targets: ['pcst4:9910']
  - job_name: 'cadvisor_pcst4'
    static_configs:
      - targets: ['pcst4:9808']
  # pcst5
  - job_name: 'nodeexporter_pcst5'
    static_configs:
      - targets: ['pcst5:9910']
  - job_name: 'cadvisor_pcst5'
    static_configs:
      - targets: ['pcst5:9808']
  # pcsd
  - job_name: 'nodeexporter_pcsd'
    static_configs:
      - targets: ['pcsd:9910']
  - job_name: 'cadvisor_pcsd'
    static_configs:
      - targets: ['pcsd:9808']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
